import ThumbsUp from "../assets/AboutAssets/ThumbsUp.svg";
import Medal from "../assets/AboutAssets/Medal.svg";
import Heart from "../assets/AboutAssets/AboutHeart.svg";
import shopProducts from "../assets/OurServiceAssets/ShopProductIcon.svg";
import browseProperties from "../assets/OurServiceAssets/BrowserPropertiesIcon.svg";
import Setting from "../assets/OurServiceAssets/SettingIcon.svg";
import { LuFacebook } from "react-icons/lu";
import { BsTwitterX } from "react-icons/bs";
import { FaInstagram } from "react-icons/fa";
import { RiPinterestLine } from "react-icons/ri";
import { FiYoutube } from "react-icons/fi";
import frame from "../assets/trendingProductsAssets/EnormousFrame.png";
import coffeeBag from "../assets/trendingProductsAssets/CoffeeBag.png";
import koalaMomMug from "../assets/trendingProductsAssets/KoalaMomMug.png";
import posterFlyer from "../assets/trendingProductsAssets/PosterFlyer.png";
import feature01 from "../assets/FeaturesAssets/feature01.png";
import feature02 from "../assets/FeaturesAssets/feature02.png";
import feature03 from "../assets/FeaturesAssets/feature03.png";
import agent01 from "../assets/FeaturesAssets/Agent01.png";
import agent02 from "../assets/FeaturesAssets/Agent02.png";
import agent03 from "../assets/FeaturesAssets/Agent01.png";
import agent04 from "../assets/FeaturesAssets/Agent01.png";
import CardImage01 from "../assets/TopCourseAssets/cardImage01.png";
import CardImage02 from "../assets/TopCourseAssets/cardImage02.png";
import CardImage03 from "../assets/TopCourseAssets/cardImage03.png";
import CardUser01 from "../assets/TopCourseAssets/cardUser01.png";
import CardUser02 from "../assets/TopCourseAssets/cardUser02.png";
import CardUser03 from "../assets/TopCourseAssets/cardUser03.png";
import card01 from "../assets/ReviewAssets/Card01.svg";
import card02 from "../assets/ReviewAssets/Card02.svg";
import card03 from "../assets/ReviewAssets/Card03.svg";
import FBIcon from "../assets/FooterAssets/FBIcon.svg";
import TwitterIcon from "../assets/FooterAssets/TwitterIcon.svg";
import BasketBallIcon from "../assets/FooterAssets/BasketBallIcon.svg";
import VIcon from "../assets/FooterAssets/VIcon.svg";
import PinterestIcon from "../assets/FooterAssets/PinterestIcon.svg";
import BeIcon from "../assets/FooterAssets/BeIcon.svg";
import LinkedInIcon from "../assets/FooterAssets/LinkedInIcon.svg";
import Pillow from "../assets/E-commerceAssets/eComerceProductsAssets/Product04.png";
import BoxMockUP from "../assets/E-commerceAssets/eComerceProductsAssets/Product03.png";
import Packaging from "../assets/E-commerceAssets/PopularCategoriesAssets/Packaging.png";
import BusinessCard from "../assets/E-commerceAssets/PopularCategoriesAssets/Business Cards.png";
import ClothingBags from "../assets/E-commerceAssets/PopularCategoriesAssets/Clothing & Bags.png";

export const menuLinks = [
  { label: "Home", to: "/" },
  { label: "Real State", to: "/realState" },
  { label: "E-Commerce", to: "/eCommerce" },
  { label: "Course", to: "/course" },
  { label: "About", to: "/about" },
  { label: "Contact", to: "/contact" },
];

export const NavItems = [
  { link: "https://www.facebook.com/", icon: <LuFacebook /> },
  { link: "https://www.facebook.com/", icon: <BsTwitterX /> },
  { link: "https://www.facebook.com/", icon: <FaInstagram /> },
  { link: "https://www.facebook.com/", icon: <RiPinterestLine /> },
  { link: "https://www.facebook.com/", icon: <FiYoutube /> },
];

export const aboutCards = [
  {
    id: 1,
    icon: ThumbsUp,
    heading: "Our company",
    para: "We’re a digital-first platform that brings together e-commerce, real estate, and online education — designed to serve all your needs in one place with ease and trust.",
  },
  {
    id: 2,
    icon: Medal,
    heading: "Our Mission",
    para: "Our goal is to simplify life by offering reliable services under one roof. We aim to empower users to shop smart, invest wisely, and learn continuously — without switching platforms.",
  },
  {
    id: 3,
    icon: Heart,
    heading: "We Love",
    para: "We love building meaningful experiences. Our passion lies in helping people grow — whether it’s through better products, smarter investments, or quality education.",
  },
];

export const OurServiceCards = [
  {
    id: 1,
    bgNum: "1",
    icon: shopProducts,
    heading: "Shop Products",
    para: "Browse a wide range of handpicked, high-quality items — from essentials to the latest trends. Everything you need, all in one place.",
  },
  {
    id: 2,
    bgNum: "2",
    icon: browseProperties,
    heading: "Browse Properties",
    para: "Discover verified real estate listings in top areas. Buy, rent, or invest with confidence through trusted agents.",
  },
  {
    id: 3,
    bgNum: "3",
    icon: Setting,
    heading: "Learn with Courses",
    para: "Learn from industry experts with flexible, online courses in tech, business, and more. Grow your skills at your own pace.",
  },
];

// export const trendingProuctsItems = [
//   {
//     id: 1,
//     type: "trending",
//     image: frame,
//     title: "Enormous Frame",
//     Price: "555.59",
//     badge: "New",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   {
//     id: 2,
//     image: coffeeBag,
//     title: "Coffee Bag",
//     Price: "901.31",
//     star: 4.5,
//     stock: 10,
//   },
//   {
//     id: 3,
//     image: koalaMomMug,
//     title: "Koala Mom Mug",
//     Price: "512.32",
//     stars: 4,
//     reviews: 50,
//     stock: 10,
//   },
//   {
//     id: 4,
//     image: posterFlyer,
//     title: "Poster Flyer",
//     Price: "376.66",
//     badge: "New",
//     stars: 5,
//     reviews: 40,
//     stock: 10,
//   },
//   {
//     id: 5,
//     image: frame,
//     title: "Enormous Frame",
//     Price: "555.59",
//     badge: "New",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   {
//     id: 6,
//     image: coffeeBag,
//     title: "Coffee Bag",
//     Price: "901.31",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   {
//     id: 7,
//     image: koalaMomMug,
//     title: "Koala Mom Mug",
//     Price: "512.32",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   {
//     id: 8,
//     image: posterFlyer,
//     title: "Poster Flyer",
//     Price: "376.66",
//     badge: "New",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   {
//     id: 9,
//     image: frame,
//     title: "Enormous Frame",
//     Price: "555.59",
//     badge: "New",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   {
//     id: 10,
//     image: coffeeBag,
//     title: "Coffee Bag",
//     Price: "901.31",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   {
//     id: 11,
//     image: koalaMomMug,
//     title: "Koala Mom Mug",
//     Price: "512.32",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   {
//     id: 12,
//     image: posterFlyer,
//     title: "Poster Flyer",
//     Price: "376.66",
//     badge: "New",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
// ];

export const featureItems = [
  {
    id: 1,
    image: feature01,
    title: "New apartment nice view",
    address: "8100 S Ashland Ave, Chicago, IL 60620, USA",
    For: "For Rent",
    bed: "3",
    bath: "1",
    parking: "1",
    Sqfeet: "1789",
    description: "Apartment",
    agentimage: agent01,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "11,000/mo",
  },
  {
    id: 2,
    image: feature02,
    title: "Renovated studio",
    address: "194 Mercer Street, 627 Broadway, New York, NY 10012, USA",
    For: "For Sale",
    bed: "3",
    bath: "1",
    parking: "1",
    Sqfeet: "1200",
    description: "Renovated studio",
    agentimage: agent02,
    agentName: "Michelle Ramirez",
    years: "5 years ago",
    amount: "540,000",
    EachSqfeet: "3,700/sq ft",
  },
  {
    id: 3,
    image: feature03,
    title: "Light and modern apartment",
    address: "2436 SW 8th St, Miami, FL 33135, USA",
    For: "For Rent",
    bed: "4",
    bath: "2",
    parking: "1",
    Sqfeet: "1200",
    description: "Apartment",
    agentimage: agent03,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "4,500/mo",
  },
  {
    id: 4,
    image: feature03,
    title: "Light and modern apartment",
    address: "2436 SW 8th St, Miami, FL 33135, USA",
    For: "For Rent",
    bed: "4",
    bath: "2",
    parking: "1",
    Sqfeet: "1200",
    description: "Apartment",
    agentimage: agent04,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "4,500/mo",
  },
  {
    id: 5,
    image: feature01,
    title: "New apartment nice view",
    address: "8100 S Ashland Ave, Chicago, IL 60620, USA",
    For: "For Rent",
    bed: "3",
    bath: "1",
    parking: "1",
    Sqfeet: "1789",
    description: "Apartment",
    agentimage: agent01,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "11,000/mo",
  },
  {
    id: 6,
    image: feature02,
    title: "Renovated studio",
    address: "194 Mercer Street, 627 Broadway, New York, NY 10012, USA",
    For: "For Sale",
    bed: "3",
    bath: "1",
    parking: "1",
    Sqfeet: "1200",
    description: "Renovated studio",
    agentimage: agent02,
    agentName: "Michelle Ramirez",
    years: "5 years ago",
    amount: "540,000",
    EachSqfeet: "3,700/sq ft",
  },
  {
    id: 7,
    image: feature03,
    title: "Light and modern apartment",
    address: "2436 SW 8th St, Miami, FL 33135, USA",
    For: "For Rent",
    bed: "4",
    bath: "2",
    parking: "1",
    Sqfeet: "1200",
    description: "Apartment",
    agentimage: agent03,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "4,500/mo",
  },
  {
    id: 8,
    image: feature03,
    title: "Light and modern apartment",
    address: "2436 SW 8th St, Miami, FL 33135, USA",
    For: "For Rent",
    bed: "4",
    bath: "2",
    parking: "1",
    Sqfeet: "1200",
    description: "Apartment",
    agentimage: agent04,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "4,500/mo",
  },
  {
    id: 9,
    image: feature01,
    title: "New apartment nice view",
    address: "8100 S Ashland Ave, Chicago, IL 60620, USA",
    For: "For Rent",
    bed: "3",
    bath: "1",
    parking: "1",
    Sqfeet: "1789",
    description: "Apartment",
    agentimage: agent01,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "11,000/mo",
  },
  {
    id: 10,
    image: feature02,
    title: "Renovated studio",
    address: "194 Mercer Street, 627 Broadway, New York, NY 10012, USA",
    For: "For Sale",
    bed: "3",
    bath: "1",
    parking: "1",
    Sqfeet: "1200",
    description: "Renovated studio",
    agentimage: agent02,
    agentName: "Michelle Ramirez",
    years: "5 years ago",
    amount: "540,000",
    EachSqfeet: "3,700/sq ft",
  },
  {
    id: 11,
    image: feature03,
    title: "Light and modern apartment",
    address: "2436 SW 8th St, Miami, FL 33135, USA",
    For: "For Rent",
    bed: "4",
    bath: "2",
    parking: "1",
    Sqfeet: "1200",
    description: "Apartment",
    agentimage: agent03,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "4,500/mo",
  },
  {
    id: 12,
    image: feature03,
    title: "Light and modern apartment",
    address: "2436 SW 8th St, Miami, FL 33135, USA",
    For: "For Rent",
    bed: "4",
    bath: "2",
    parking: "1",
    Sqfeet: "1200",
    description: "Apartment",
    agentimage: agent04,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "4,500/mo",
  },
];

export const ourCourseCards = [
  {
    id: 1,
    topimage: CardImage01,
    userIamge: CardUser01,
    name: "Jason William",
    ratingValue: "4,9/50",
    title: "Full-stack Back end",
    time: "06 hr 50 mins",
    lecture: "29 Lecture",
    beforeAmount: "$350",
    afterAmount: "120",
  },
  {
    id: 2,
    topimage: CardImage02,
    userIamge: CardUser02,
    name: "Alexio Marlo",
    ratingValue: "4,9/50",
    title: "Beginner Aljabar",
    time: "05 hr 30 mins",
    lecture: "15 Lecture",
    beforeAmount: "$250",
    afterAmount: "80",
  },
  {
    id: 3,
    topimage: CardImage03,
    userIamge: CardUser03,
    name: "Amelia Jenaka",
    ratingValue: "4,9/50",
    title: "Public Speaking for MC",
    time: "12 hr 75 mins",
    lecture: "29 Lecture",
    beforeAmount: "$650",
    afterAmount: "310",
  },
];

export const reviewSectionCards = [
  { id: 1, icon: card01, lebal: "Satisfied Customers", amount: "5,000" },
  { id: 2, icon: card02, lebal: "Properties Listed", amount: "1,200" },
  { id: 3, icon: card03, lebal: "Products Delivered", amount: "20,000" },
];

export const footerSocialLinks = [
  {
    icon: FBIcon,
    link: "https://www.facebook.com/",
  },
  {
    icon: TwitterIcon,
    link: "https://x.com/",
  },
  {
    icon: BasketBallIcon,
    link: "/",
  },
  {
    icon: VIcon,
    link: "/",
  },
  {
    icon: PinterestIcon,
    link: "https://www.pinterest.com/",
  },
  {
    icon: BeIcon,
    link: "/",
  },
  {
    icon: LinkedInIcon,
    link: "/",
  },
];

export const eCommerceProuctsItems = [
  {
    id: 1,
    image: Pillow,
    title: "Pillow",
    Price: "279.41",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 2,
    image: posterFlyer,
    title: "Poster Flyer",
    Price: "376.66",
    badge: "New",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 3,
    image: BoxMockUP,
    title: "Box MockUp",
    Price: "512.32",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 4,
    image: frame,
    title: "Enormous Frame",
    Price: "555.59",
    badge: "New",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 5,
    image: Pillow,
    title: "Pillow",
    Price: "279.41",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 6,
    image: posterFlyer,
    title: "Poster Flyer",
    Price: "376.66",
    badge: "New",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 7,
    image: BoxMockUP,
    title: "Box MockUp",
    Price: "512.32",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 8,
    image: frame,
    title: "Enormous Frame",
    Price: "555.59",
    badge: "New",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 9,
    image: Pillow,
    title: "Pillow",
    Price: "279.41",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 10,
    image: posterFlyer,
    title: "Poster Flyer",
    Price: "376.66",
    badge: "New",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 11,
    image: BoxMockUP,
    title: "Box MockUp",
    Price: "512.32",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
  {
    id: 12,
    image: frame,
    title: "Enormous Frame",
    Price: "555.59",
    badge: "New",
    stock: 10,
    stars: 4.5,
    reviews: 50,
  },
];

// export const MostSellingProucts = [
//   {
//     id: 1,
//     image: Pillow,
//     title: "Pillow",
//     Price: "279.41",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   {
//     id: 2,
//     image: posterFlyer,
//     title: "Poster Flyer",
//     Price: "376.66",
//     badge: "New",
//     stars: 4.5,
//     reviews: 50,
//     stock: 10,
//   },
//   { id: 3, image: BoxMockUP, title: "Box MockUp", Price: "512.32", stock: 10 },
//   {
//     id: 4,
//     image: frame,
//     title: "Enormous Frame",
//     Price: "555.59",
//     badge: "New",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
//   { id: 5, image: Pillow, title: "Pillow", Price: "279.41", stock: 10 },
//   {
//     id: 6,
//     image: posterFlyer,
//     title: "Poster Flyer",
//     Price: "376.66",
//     badge: "New",
//     stars: 3,
//     reviews: 30,
//     stock: 10,
//   },
//   { id: 7, image: BoxMockUP, title: "Box MockUp", Price: "512.32" },
//   {
//     id: 8,
//     image: frame,
//     title: "Enormous Frame",
//     Price: "555.59",
//     badge: "New",
//     stars: 5,
//     reviews: 20,
//     stock: 10,
//   },
//   { id: 9, image: Pillow, title: "Pillow", Price: "279.41" },
//   {
//     id: 10,
//     image: posterFlyer,
//     title: "Poster Flyer",
//     Price: "376.66",
//     badge: "New",
//     stars: 1,
//     reviews: 60,
//     stock: 10,
//   },
//   { id: 11, image: BoxMockUP, title: "Box MockUp", Price: "512.32", stock: 10 },
//   {
//     id: 12,
//     image: frame,
//     title: "Enormous Frame",
//     Price: "555.59",
//     badge: "New",
//     stars: 5,
//     reviews: 60,
//     stock: 10,
//   },
// ];

export const eCommerceReviewSectionCards = [
  { id: 1, icon: card01, lebal: "Items shipped sine 2013", amount: "375M" },
  {
    id: 2,
    icon: card02,
    lebal: "Customer quality satisfaction",
    amount: "10697",
  },
  { id: 3, icon: card03, lebal: "Items fulfilled every month", amount: "13M" },
];

export const popularCards = [
  { id: 1, name: "Packaging", image: Packaging },
  { id: 2, name: "Business Cards", image: BusinessCard },
  { id: 3, name: "Clothing & Bags", image: ClothingBags },
];

// export const productCollections = {
//   trending: trendingProuctsItems,
//   mostselling: MostSellingProucts,
// };

export const allProducts = [
  // trending Products
  {
    id: 1,
    type: "trending",
    image: frame,
    title: "Enormous Frame",
    Price: "555.59",
    badge: "New",
    stars: 5,
    reviews: 60,
    stock: 10,
  },
  {
    id: 2,
    type: "trending",
    image: coffeeBag,
    title: "Coffee Bag",
    Price: "901.31",
    badge: "Hot",
    stars: 4.5,
    reviews: 30,
    stock: 10,
  },
  {
    id: 3,
    type: "trending",
    image: koalaMomMug,
    title: "Koala Mom Mug",
    Price: "512.32",
    badge: "New",
    stars: 4,
    reviews: 50,
    stock: 10,
  },
  {
    id: 4,
    type: "trending",
    image: posterFlyer,
    title: "Poster Flyer",
    Price: "376.66",
    badge: "New",
    stars: 5,
    reviews: 40,
    stock: 10,
  },

  // Most Selling Products
  {
    id: 5,
    type: "mostselling",
    image: Pillow,
    title: "Pillow",
    Price: "279.41",
    badge: "Top",
    stars: 5,
    reviews: 60,
    stock: 10,
  },
  {
    id: 6,
    type: "mostselling",
    image: posterFlyer,
    title: "Poster Flyer",
    Price: "376.66",
    badge: "New",
    stars: 4.5,
    reviews: 50,
    stock: 10,
  },
  {
    id: 7,
    type: "mostselling",
    image: BoxMockUP,
    title: "Box MockUp",
    Price: "512.32",
    badge: "Best",
    stars: 4,
    reviews: 30,
    stock: 10,
  },
  {
    id: 8,
    type: "mostselling",
    image: frame,
    title: "Enormous Frame",
    Price: "555.59",
    badge: "New",
    stars: 5,
    reviews: 60,
    stock: 10,
  },

  // Best Seller Products
  {
    id: 9,
    type: "bestseller",
    image: Pillow,
    title: "Pillow",
    Price: "279.41",
    badge: "Top",
    stars: 5,
    reviews: 60,
    stock: 10,
  },
  {
    id: 10,
    type: "bestseller",
    image: posterFlyer,
    title: "Poster Flyer",
    Price: "376.66",
    badge: "New",
    stars: 4.5,
    reviews: 50,
    stock: 10,
  },
  {
    id: 11,
    type: "bestseller",
    image: BoxMockUP,
    title: "Box MockUp",
    Price: "512.32",
    badge: "Best",
    stars: 4,
    reviews: 30,
    stock: 10,
  },
  {
    id: 12,
    type: "bestseller",
    image: frame,
    title: "Enormous Frame",
    Price: "555.59",
    badge: "New",
    stars: 5,
    reviews: 60,
    stock: 10,
  },
];

export const mockData = [
  // ---------- Real Estate / Feature Properties ----------
  {
    id: 140,
    category: "property",
    type: "bestseller",
    image: feature01,
    title: "New apartment nice view",
    address: "8100 S Ashland Ave, Chicago, IL 60620, USA",
    For: "For Rent",
    bed: "3",
    bath: "1",
    parking: "1",
    Sqfeet: "1789",
    description: "Apartment",
    agentimage: agent01,
    agentName: "Samuel Palmer",
    years: "5 years ago",
    amount: "11,000/mo",
  },
  {
    id: 141,
    category: "property",
    type: "bestseller",
    image: feature02,
    title: "Renovated studio",
    address: "194 Mercer Street, New York, NY 10012, USA",
    For: "For Sale",
    bed: "3",
    bath: "1",
    parking: "1",
    Sqfeet: "1200",
    description: "Renovated studio",
    agentimage: agent02,
    agentName: "Michelle Ramirez",
    years: "5 years ago",
    amount: "540,000",
    EachSqfeet: "3,700/sq ft",
  },
];
